# frozen_string_literal: true

require_relative "projection"

module RubyLsp
  module RubyLspSlim
    # Internal request input only: AST locations, tokens and code-unit caches all
    # stay in generated bytes. Request/response adapters translate at the editor
    # boundary; partially relocating AST locations would leave caches inconsistent.
    class GeneratedDocument < RubyLsp::RubyDocument
      BYTE_OFFSETS = ->(offset) { offset }

      def initialize(**options)
        super
        @code_units_cache = BYTE_OFFSETS
      end

      def parse!
        changed = super
        @code_units_cache = BYTE_OFFSETS
        changed
      end

      # Native requests use ERB's embedded-language path, not Slim's language id.
      # This is never a Store document; should_index? is an additional safeguard
      # against publishing generated declarations into the persistent Ruby index.
      def language_id = :erb
      def should_index? = false

      def find_index_by_position(start_position, end_position = nil)
        positions = Positions.new(source, Encoding::UTF_8)
        [positions.byte_offset(start_position), end_position && positions.byte_offset(end_position)]
      end
    end
  end
end
